### ISSUE TITLE
Issue when used as submodule

### ISSUE THREAD

**Issue by TheLongRunSmoke** [bxparks/AUnit#77] opened 2021-10-16 10:39 UTC
Hi. For some reasons, I can't use AUnit as git submodule. When installed using Arduino IDE all works fine.

In my setup I got
```
In file included from ExternalTests.cpp:12:0:
AUnitMetaTest.h:13:12: fatal error: AUnit.h: No such file or directory
compilation terminated.
exit status 1
Error compiling for board Arduino Pro or Pro Mini.
```

**Steps to reproduce:**
1. Create sketch in empty folder.
2. Init git repo.
3. Add AUnit as submodule. 
```
 git submodule add git@github.com:bxparks/AUnit.git
```
4. Add minimal testing code in to the sketch.
```
#include "AUnit/src/AUnit.h"

test(submodule_include_test){
  int x = 1;
  assertEqual(x, 1);
}
```
5. Try to compile and get various errors.

**Comment by TheLongRunSmoke** [comment] 2021-10-17 06:07
Have same issue even if place it in ```libraries/```.
However, when I remove ```AUnit/tests``` folder it's start to compile and work normally, from any path. 
Looks like you unintentionally use includes with diamond brackets in tests. 

This need to be fixed. Libraries outside of source folder is generally a bad idea, due possibilities of version conflicts between projects.

**Comment by bxparks** [comment] 2021-10-17 15:54
I'm not sure I understand what the problem is, what your propose fix is. I think it would be helpful if you included more info about your environment, your source directory structure, and the tools that you using.

You say that AUnit works when installed using the Arduino IDE. That is the installation process which is supported. I don't use git submodules, I have never tested it, I don't mention it in my docs, so I don't what your source tree looks like, so I have no idea what is broken. I normally use diamond brackets very intentionally.

**Comment by bxparks** [comment] 2021-10-18 16:34
I agree that your directory structure is better in many ways, and I even attempted to use something like when I first started working with Arduino. But Arduino does not support it, and it just broke too many things. I find it too difficult and time consuming to fight Arduino's design decisions, so my suggestion is to just go with the Arduino Library Manager defaults.

**Comment by TheLongRunSmoke** [comment] 2021-10-19 04:41
Ok. For now I will use a fork without ```tests``` folder.

**Comment by bxparks** [comment] 2021-11-03 01:24
Closing this, but moving to Discussions for future reference.

**Closed by bxparks** 2021-11-03 01:24 UTC
